### ISSUE TITLE
Bytecode tracking issue

### ISSUE THREAD

**Issue by pca006132** [pca006132/sscad#2]
- [ ] Basic bytecode evaluator implementation.
- [ ] AST to bytecode translation.
- [ ] File scope (compile unit) variable handling.
- [ ] Fast instructions for constant addition, indexing.
- [ ] Optimize reference counting.
- [ ] Optimize memory access.
- [ ] Function/Module evaluation cache.
